#!/bin/sh

case $1 in
	i|install)
    if [ -f bower.json ]; then
        bower install --allow-root
    fi

    if [ -f package.json ]; then
        npm install
    fi

    if [ -f Gemfile ]; then
        bundle install
    fi
    ;;
  t|test)
    htmlproofer $2 --allow-hash-href --check-html --http-status-ignore 0
    ;;
  *)
    CMD="jekyll ${@}"

    if [ -f Gemfile ]; then
        CMD="bundle exec $CMD"
    fi

    echo "$CMD"

    eval $CMD
    ;;
esac
